swagger: '2.0'
info:
  title: SNA API
  description: SNA project API
  version: "1.0.0"
# the domain of the service
host: sna.ro
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /questions:
    get:
      summary: Questions
      description: |
        The list of questions to answer for the institution.
      tags:
        - Questions
      responses:
        200:
          description: An array of questions
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Question:
    type: object
    properties:
      text:
        type: string
        description: text of the question.
      answerType:
        type: string
        description: Description of answer type.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string

