-- MySQL Script generated by MySQL Workbench
-- 01/19/17 12:58:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema websoft_sna
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `websoft_sna` ;

-- -----------------------------------------------------
-- Schema websoft_sna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `websoft_sna` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `websoft_sna` ;

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `admin` (
  `ID_Admin` INT(2) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(200) NOT NULL,
  `Password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ID_Admin`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bunuri_confiscate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bunuri_confiscate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bunuri_confiscate` (
  `ID_Bun` INT(3) NOT NULL AUTO_INCREMENT,
  `Titlu_En` VARCHAR(150) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Titlu_Ro` VARCHAR(150) NOT NULL,
  `Titlu_Fr` VARCHAR(150) NOT NULL,
  `Descriere_En` TEXT CHARACTER SET 'latin1' NOT NULL,
  `Descriere_Ro` TEXT NOT NULL,
  `Descriere_Fr` TEXT NOT NULL,
  `ID_Categorie_Bunuri` INT(2) NOT NULL,
  `Poza` VARCHAR(250) NOT NULL,
  `Latitudine` VARCHAR(250) NOT NULL,
  `Longitudine` VARCHAR(250) NOT NULL,
  `Data_Publicare` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_Bun`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cariere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cariere` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cariere` (
  `ID_Cariere` INT(5) NOT NULL AUTO_INCREMENT,
  `Titlu_Ro` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Titlu_En` TINYTEXT CHARACTER SET 'utf8' NOT NULL,
  `Titlu_Fr` TINYTEXT CHARACTER SET 'utf8' NOT NULL,
  `Descriere_Ro` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Descriere_En` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Descriere_Fr` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Tip` INT(1) NOT NULL,
  PRIMARY KEY (`ID_Cariere`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_romanian_ci;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `Titlu_Ro` ON `cariere` (`Titlu_Ro` ASC);

SHOW WARNINGS;
CREATE FULLTEXT INDEX `Titlu_Ro_2` ON `cariere` (`Titlu_Ro` ASC);

SHOW WARNINGS;
CREATE FULLTEXT INDEX `Descriere_Ro` ON `cariere` (`Descriere_Ro` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categorie_bunuri_confiscate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorie_bunuri_confiscate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categorie_bunuri_confiscate` (
  `ID_Categorie_Bunuri` INT(11) NOT NULL AUTO_INCREMENT,
  `Categ_Ro` VARCHAR(250) NOT NULL,
  `Categ_En` VARCHAR(250) NOT NULL,
  `Categ_Fr` VARCHAR(250) NOT NULL,
  `Prioritate` INT(2) NOT NULL,
  PRIMARY KEY (`ID_Categorie_Bunuri`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categorii`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorii` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categorii` (
  `id_c` INT(3) NOT NULL AUTO_INCREMENT,
  `denumire_c` VARCHAR(50) NOT NULL,
  `tip` INT(1) NOT NULL,
  `prioritate` INT(2) NOT NULL,
  PRIMARY KEY (`id_c`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categorii_cariere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorii_cariere` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categorii_cariere` (
  `ID_Categ_Cariere` INT(11) NOT NULL AUTO_INCREMENT,
  `Categ_Ro` TINYTEXT CHARACTER SET 'utf8' NOT NULL,
  `Categ_En` TINYTEXT NOT NULL,
  `Categ_FR` TINYTEXT NOT NULL,
  `Prioritate` INT(2) NOT NULL,
  PRIMARY KEY (`ID_Categ_Cariere`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categorii_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorii_media` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categorii_media` (
  `ID_Categ_Media` INT(11) NOT NULL AUTO_INCREMENT,
  `Categ_Ro` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `Categ_En` VARCHAR(250) NOT NULL,
  `Categ_Fr` VARCHAR(250) NOT NULL,
  `Prioritate` INT(2) NOT NULL,
  PRIMARY KEY (`ID_Categ_Media`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chestionar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chestionar` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chestionar` (
  `id_intrebare` INT(4) NOT NULL AUTO_INCREMENT,
  `intrebare` TEXT CHARACTER SET 'utf8' NOT NULL,
  `req` VARCHAR(1) NULL DEFAULT NULL,
  `type` INT(2) NOT NULL,
  `valoare` VARCHAR(10) NOT NULL,
  `char` VARCHAR(10) NOT NULL,
  `numeric` INT(1) NULL DEFAULT NULL,
  `chart` INT(11) NULL DEFAULT NULL,
  `pas` INT(2) NOT NULL,
  PRIMARY KEY (`id_intrebare`))
ENGINE = InnoDB
AUTO_INCREMENT = 143
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cookie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cookie` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cookie` (
  `cookie` INT(7) NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `doc_news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doc_news` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `doc_news` (
  `document` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`document`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `documente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `documente` (
  `ID_Doc` INT(5) NOT NULL AUTO_INCREMENT,
  `id_c` INT(2) NOT NULL,
  `Document` TINYTEXT NOT NULL,
  PRIMARY KEY (`ID_Doc`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `elemente_prima_pagina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elemente_prima_pagina` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `elemente_prima_pagina` (
  `ID_Element` INT(4) NOT NULL AUTO_INCREMENT,
  `Titlu` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `Link` VARCHAR(150) NOT NULL,
  `Descriere` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Imagine` VARCHAR(100) NOT NULL,
  `Activ` INT(1) NOT NULL,
  `Prioritate` INT(1) NOT NULL,
  PRIMARY KEY (`ID_Element`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `galerie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galerie` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `galerie` (
  `id_gal` INT(5) NOT NULL AUTO_INCREMENT,
  `poza` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_gal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `infografice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infografice` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `infografice` (
  `id_info` INT(5) NOT NULL AUTO_INCREMENT,
  `id_j` INT(3) NOT NULL,
  `id_intrebare` INT(3) NOT NULL,
  `descriere` TEXT CHARACTER SET 'utf8' NOT NULL,
  `poza` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_info`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `judete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judete` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `judete` (
  `id_j` INT(11) NOT NULL AUTO_INCREMENT,
  `judet` VARCHAR(80) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_j`))
ENGINE = InnoDB
AUTO_INCREMENT = 130
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leg_cariere_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leg_cariere_doc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `leg_cariere_doc` (
  `ID_Cariere` INT(5) NOT NULL,
  `doc` VARCHAR(250) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leg_cat_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leg_cat_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `leg_cat_user` (
  `id_user` INT(5) NOT NULL,
  `id_c` INT(2) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leg_media_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leg_media_doc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `leg_media_doc` (
  `ID_Media` INT(5) NOT NULL,
  `doc` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leg_pag_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leg_pag_doc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `leg_pag_doc` (
  `id_leg` INT(5) NOT NULL AUTO_INCREMENT,
  `ID_Pagina` INT(5) NOT NULL,
  `doc` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_leg`))
ENGINE = InnoDB
AUTO_INCREMENT = 104
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `media` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `media` (
  `ID_Media` INT(5) NOT NULL AUTO_INCREMENT,
  `Titlu_Ro` TINYTEXT CHARACTER SET 'utf8' NOT NULL,
  `Titlu_En` TINYTEXT CHARACTER SET 'utf8' NOT NULL,
  `Titlu_Fr` TINYTEXT CHARACTER SET 'utf8' NOT NULL,
  `Descriere_Ro` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Descriere_En` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Descriere_Fr` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Poza` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `Data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Tip` INT(1) NOT NULL,
  PRIMARY KEY (`ID_Media`))
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_romanian_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `menu` (
  `ID_Menu` INT(11) NOT NULL AUTO_INCREMENT,
  `Menu_En` VARCHAR(150) NOT NULL,
  `Menu_Ro` VARCHAR(150) NOT NULL,
  `Menu_Fr` VARCHAR(150) NOT NULL,
  `Link` VARCHAR(250) NULL DEFAULT NULL,
  `Prioritate` INT(2) NOT NULL,
  PRIMARY KEY (`ID_Menu`))
ENGINE = MyISAM
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newsletter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsletter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newsletter` (
  `emails` VARCHAR(250) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pagini`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagini` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pagini` (
  `ID_Pagina` INT(4) NOT NULL AUTO_INCREMENT,
  `Titlu` VARCHAR(250) NOT NULL,
  `ID_Menu_Leg` INT(3) NOT NULL,
  `ID_Submenu_Leg` INT(3) NOT NULL,
  `ID_Ssubmenu_Leg` INT(3) NOT NULL,
  `Desc_En` TEXT NOT NULL,
  `Desc_Fr` TEXT NOT NULL,
  `Desc_Ro` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID_Pagina`))
ENGINE = MyISAM
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `poze_bunuri_confiscate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poze_bunuri_confiscate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `poze_bunuri_confiscate` (
  `ID_Bun` INT(5) NOT NULL,
  `Poza` VARCHAR(250) NOT NULL,
  `Prioritate` INT(2) NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `raspunsuri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raspunsuri` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `raspunsuri` (
  `id_rasp` INT(6) NOT NULL AUTO_INCREMENT,
  `id_user` INT(5) NOT NULL,
  `id_intrebare` INT(4) NOT NULL,
  `raspuns` TEXT NULL DEFAULT NULL,
  `data_rasp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `an` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id_rasp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `slider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slider` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `slider` (
  `ID_Slider` INT(11) NOT NULL AUTO_INCREMENT,
  `Titlu_Ro` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `Subtitlu_Ro` VARCHAR(50) COLLATE 'utf32_romanian_ci' NOT NULL,
  `Subtitlu_En` VARCHAR(50) NOT NULL,
  `Subtitlu_Fr` VARCHAR(50) NOT NULL,
  `Titlu_En` VARCHAR(250) NOT NULL,
  `Titlu_Fr` VARCHAR(250) NOT NULL,
  `Link` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `Poza` VARCHAR(250) NOT NULL,
  `Stare` INT(11) NOT NULL,
  `Prioritate` INT(11) NOT NULL,
  PRIMARY KEY (`ID_Slider`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ssubmenu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssubmenu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ssubmenu` (
  `ID_Ssubmenu` INT(3) NOT NULL AUTO_INCREMENT,
  `ID_Submenu` INT(3) NOT NULL,
  `Ssubmenu_En` VARCHAR(150) NOT NULL,
  `Ssubmenu_Ro` VARCHAR(150) NOT NULL,
  `Ssubmenu_Fr` VARCHAR(250) NOT NULL,
  `Link` VARCHAR(150) NOT NULL,
  `Prioritate` INT(2) NOT NULL,
  PRIMARY KEY (`ID_Ssubmenu`))
ENGINE = MyISAM
AUTO_INCREMENT = 77
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `submenu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `submenu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `submenu` (
  `ID_Submenu` INT(3) NOT NULL AUTO_INCREMENT,
  `ID_Menu` INT(3) NOT NULL,
  `Submenu_En` VARCHAR(150) NOT NULL,
  `Submenu_Ro` VARCHAR(150) NOT NULL,
  `Submenu_Fr` VARCHAR(250) NOT NULL,
  `Link` VARCHAR(250) NOT NULL,
  `Coloana` INT(1) NOT NULL,
  `Prioritate` INT(2) NOT NULL,
  PRIMARY KEY (`ID_Submenu`))
ENGINE = MyISAM
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sume` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sume` (
  `id_suma` INT(1) NOT NULL AUTO_INCREMENT,
  `suma` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_suma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sume_c`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sume_c` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sume_c` (
  `id_suma` INT(1) NOT NULL,
  `suma_c` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_suma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_suma` ON `sume_c` (`id_suma` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `t_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t_users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `t_users` (
  `judet` VARCHAR(100) NOT NULL,
  `oras` VARCHAR(150) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_docs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_docs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_docs` (
  `id_doc` INT(6) NOT NULL AUTO_INCREMENT,
  `id_user` INT(5) NOT NULL,
  `doc` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_doc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `ID_User` INT(5) NOT NULL AUTO_INCREMENT,
  `Cookie_Log` VARCHAR(250) NOT NULL,
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `judet` INT(2) NOT NULL,
  `localitate` VARCHAR(50) NOT NULL,
  `nume` VARCHAR(100) NOT NULL,
  `subord` VARCHAR(5) NOT NULL,
  `titular` VARCHAR(100) NOT NULL,
  `adresa` VARCHAR(250) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `nr_angajati` VARCHAR(10) NOT NULL,
  `categorii_prof` TEXT NOT NULL,
  `acte_normative` TEXT NOT NULL,
  `nr_rasp` VARCHAR(10) NOT NULL,
  `nr_domenii` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_User`))
ENGINE = MyISAM
AUTO_INCREMENT = 5001
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
